#!/usr/bin/env bash
# Generates language-specific realm files from the canonical words/realms.json.
# Run after editing realms.json to update Go, Python, and JS implementations.
set -euo pipefail
cd "$(dirname "$0")"

REALMS=words/realms.json

echo "Syncing word lists from $REALMS..."

# --- Go: go/realms.go ---
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['package sigil', '', '// Generated by sync-words.sh — do not edit manually.', '', 'type Realm struct {', '\tAdjectives []string', '\tNouns      []string', '}', '', 'var Realms = map[string]Realm{']

for realm, words in data.items():
    lines.append(f'\t\"{realm}\": {{')
    adjs = ', '.join(f'\"{w}\"' for w in words['adjectives'])
    lines.append(f'\t\tAdjectives: []string{{{adjs}}},')
    nouns = ', '.join(f'\"{w}\"' for w in words['nouns'])
    lines.append(f'\t\tNouns:      []string{{{nouns}}},')
    lines.append('\t},')

lines.append('}')
lines.append('')

with open('go/realms.go', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ go/realms.go')
"

# --- Python: python/realm_sigil/realms.py ---
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['# Generated by sync-words.sh — do not edit manually.', '', 'REALMS = {']

for realm, words in data.items():
    lines.append(f'    \"{realm}\": {{')
    lines.append(f'        \"adjectives\": {json.dumps(words[\"adjectives\"])},')
    lines.append(f'        \"nouns\": {json.dumps(words[\"nouns\"])},')
    lines.append('    },')

lines.append('}')
lines.append('')

with open('python/realm_sigil/realms.py', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ python/realm_sigil/realms.py')
"

# --- JS: js/realms.js ---
python3 -c "
import json

with open('$REALMS') as f:
    data = json.load(f)

lines = ['// Generated by sync-words.sh — do not edit manually.', '', 'const REALMS = {']

for realm, words in data.items():
    lines.append(f'  {realm}: {{')
    lines.append(f'    adjectives: {json.dumps(words[\"adjectives\"])},')
    lines.append(f'    nouns: {json.dumps(words[\"nouns\"])},')
    lines.append('  },')

lines.append('};')
lines.append('')
lines.append('module.exports = { REALMS };')
lines.append('')

with open('js/realms.js', 'w') as f:
    f.write('\n'.join(lines))
print('  ✓ js/realms.js')
"

echo "Done. All realm files synced."
