package sigil

// Generated by sync-words.sh — do not edit manually.

type Realm struct {
	Adjectives []string
	Nouns      []string
}

var Realms = map[string]Realm{
	"fantasy": {
		Adjectives: []string{"Arcane", "Blazing", "Celestial", "Draconic", "Eldritch", "Fabled", "Gilded", "Hallowed", "Infernal", "Jade", "Kindled", "Luminous", "Mythic", "Noble", "Obsidian", "Primal", "Radiant", "Spectral", "Twilight", "Valiant"},
		Nouns:      []string{"Aegis", "Beacon", "Crown", "Dominion", "Ember", "Forge", "Grimoire", "Herald", "Insignia", "Jewel", "Keystone", "Lantern", "Monolith", "Nexus", "Oracle", "Pinnacle", "Quartz", "Relic", "Sigil", "Throne"},
	},
	"tarot": {
		Adjectives: []string{"Arcane", "Blessed", "Charmed", "Destined", "Enchanted", "Fateful", "Guiding", "Hidden", "Illumined", "Judging", "Karmic", "Liminal", "Moonlit", "Numbered", "Ordained", "Portentous", "Querent", "Reversed", "Starlit", "Turning"},
		Nouns:      []string{"Amulet", "Blade", "Chalice", "Diviner", "Emperor", "Fool", "Guardian", "Hermit", "Initiate", "Justice", "Knight", "Lovers", "Magician", "Nomad", "Ouroboros", "Pentacle", "Querent", "Rosette", "Scepter", "Tower"},
	},
	"oracle": {
		Adjectives: []string{"Augured", "Beckoning", "Clairvoyant", "Delphic", "Ethereal", "Foretold", "Glimpsed", "Hushed", "Intuited", "Judicious", "Knowing", "Lucid", "Murmured", "Nascent", "Omniscient", "Prophetic", "Quieted", "Resonant", "Scried", "Veiled"},
		Nouns:      []string{"Augury", "Bones", "Cipher", "Doctrine", "Echo", "Foresight", "Gaze", "Hymn", "Insight", "Judgment", "Kenning", "Lens", "Mirror", "Notion", "Omen", "Prophecy", "Question", "Revelation", "Sight", "Truth"},
	},
	"void": {
		Adjectives: []string{"Abyssal", "Boundless", "Collapsed", "Drifting", "Entropic", "Fractured", "Galactic", "Hollow", "Infinite", "Jagged", "Kinetic", "Liminal", "Muted", "Null", "Obsidian", "Phantom", "Quantum", "Ruptured", "Silent", "Twisted"},
		Nouns:      []string{"Abyss", "Breach", "Cascade", "Drift", "Expanse", "Fragment", "Glitch", "Horizon", "Interval", "Junction", "Knot", "Lattice", "Membrane", "Nexus", "Orbit", "Paradox", "Rift", "Shade", "Threshold", "Vertex"},
	},
	"forge": {
		Adjectives: []string{"Annealed", "Bolted", "Carbonized", "Dense", "Electric", "Flux", "Galvanized", "Hardened", "Ignited", "Joined", "Keen", "Laminated", "Molten", "Nitrided", "Oxidized", "Pressed", "Quenched", "Riveted", "Sintered", "Tempered"},
		Nouns:      []string{"Anvil", "Bellows", "Crucible", "Die", "Engine", "Furnace", "Gear", "Hammer", "Ingot", "Jig", "Kiln", "Lathe", "Mandrel", "Nozzle", "Oven", "Piston", "Quench", "Rivet", "Spark", "Tongs"},
	},
	"signal": {
		Adjectives: []string{"Amplified", "Broadcast", "Channeled", "Decoded", "Echoing", "Filtered", "Grounded", "Harmonic", "Isolated", "Jittered", "Keyed", "Latched", "Modulated", "Narrowed", "Oscillating", "Pulsed", "Quantized", "Relayed", "Synced", "Tuned"},
		Nouns:      []string{"Antenna", "Beacon", "Carrier", "Diode", "Emitter", "Frequency", "Gate", "Harmonic", "Impulse", "Junction", "Keystone", "Link", "Modem", "Node", "Oscillator", "Pulse", "Qubit", "Relay", "Signal", "Transponder"},
	},
	"stellar": {
		Adjectives: []string{"Ascending", "Binary", "Cosmic", "Distant", "Expanding", "Flaring", "Graviton", "Helical", "Ionized", "Jovian", "Kepler", "Lunar", "Magnetic", "Nebular", "Orbital", "Pulsating", "Quantum", "Radiant", "Solar", "Tidal"},
		Nouns:      []string{"Aurora", "Bolide", "Corona", "Dwarf", "Eclipse", "Firmament", "Galaxy", "Halo", "Ion", "Jet", "Kuiper", "Luminance", "Meteor", "Nova", "Orbit", "Pulsar", "Quasar", "Remnant", "Supernova", "Zenith"},
	},
}
